Hack for API change to test.support.bigmemtest
This gets the two big memory tests to run under Python 3.1
but the big memory decompression test fails as below:

ERROR: test_decompressor_bigmem (__main__.CompressorDecompressorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File test_lzma.py, line 19, in wrapper
    return f(self, 5147)
  File test_lzma.py, line 224, in test_decompressor_bigmem
    block = random.getrandbits(blocksize * 8).to_bytes(blocksize, little)
AttributeError: 'int' object has no attribute 'to_bytes'