Fix bytes type code 'y' -> 's' under Python 2.
Without this, using 'y' would confuse Python 2's getargs.c and resulted
in very odd exception messages like this:

TypeError: must be impossible<bad format char>, not str

Adding a little debugging to getargs.c and recompiling Python 2 helped
explain what was going wrong - the case default message would be much
more useful if it included the unknown type character (here 'y').

Under Python 2, using 's' for string appears to be appropriate. With
this fix, more of the unit tests now pass under Python 2.6 and 2.7
(although the later needs a manual fix to avoid clashing definitions
of PyErr_NewExceptionWithDoc to compile).