Travis pypy3 currently too old? pypy3 v5.10.0
Breaks with:

ImportError: /home/travis/virtualenv/pypy3.5-5.8.0/site-packages/backports/lzma/_lzma.pypy3-58-x86_64-linux-gnu.so: undefined symbol: PyUnicode_DecodeUTF8Stateful