Revert testing under Python 3.3 on TravisCI (compile fails)
This reverts commit bff62686f2918f75e9d9dd50db451037c204ad59.

Bulding on Python 3.3 will need a little work, e.g.
backports/lzma/_lzmamodule.c:1273:1: error: unknown type name ‘PyModuleDef’